# Generated by Django 2.1.3 on 2018-11-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='image',
            field=models.ImageField(default='/static/images/thing_images/default/default_cabbage.jpg', upload_to=''),
        ),
    ]
