# Generated by Django 2.1.3 on 2018-11-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_thing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
