# Generated by Django 2.1.3 on 2018-11-15 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_auto_20181115_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thing',
            name='image',
        ),
    ]
